export const initialDevices = [
  {
    id: 'dev-1',
    name: 'Living Room Pendant',
    type: 'light',
    room: 'Living Room',
    isOn: true,
    value: 75,
    metricUnit: '%',
    energyUsage: 28,
    status: 'online',
    lastSeen: 'Just now',
  },
  {
    id: 'dev-2',
    name: 'Nest Thermostat v3',
    type: 'thermostat',
    room: 'Living Room',
    isOn: true,
    value: 72,
    metricUnit: '°F',
    energyUsage: 45,
    status: 'online',
    lastSeen: '1 minute ago',
  },
  {
    id: 'dev-3',
    name: 'Entertainment Hub Plug',
    type: 'smart-plug',
    room: 'Living Room',
    isOn: true,
    value: 100,
    metricUnit: '%',
    energyUsage: 140,
    status: 'online',
    lastSeen: '3 minutes ago',
  },
  {
    id: 'dev-4',
    name: 'Front Door Deadbolt',
    type: 'lock',
    room: 'Garage',
    isOn: true, // true = locked, false = unlocked
    value: 100,
    metricUnit: 'Locked',
    energyUsage: 2,
    status: 'online',
    lastSeen: 'Just now',
  },
  {
    id: 'dev-5',
    name: 'Driveway Floodlight',
    type: 'light',
    room: 'Garage',
    isOn: false,
    value: 0,
    metricUnit: '%',
    energyUsage: 0,
    status: 'online',
    lastSeen: '10 mins ago',
  },
  {
    id: 'dev-6',
    name: 'Backyard Cam AI',
    type: 'camera',
    room: 'Backyard',
    isOn: true,
    value: 100,
    metricUnit: 'FPS',
    energyUsage: 12,
    status: 'online',
    lastSeen: 'Just now',
    alert: 'Intrusion detection armed',
  },
  {
    id: 'dev-7',
    name: 'Kitchen Coffee Brewer',
    type: 'smart-plug',
    room: 'Kitchen',
    isOn: false,
    value: 0,
    metricUnit: 'W',
    energyUsage: 0,
    status: 'standby',
    lastSeen: '4 mins ago',
  },
  {
    id: 'dev-8',
    name: 'RoboVac Clean sweep',
    type: 'vacuum',
    room: 'Living Room',
    isOn: false,
    value: 30, // Battery charge percent
    metricUnit: '%',
    energyUsage: 15, // Dock charging load
    status: 'standby',
    lastSeen: '2 hours ago',
  },
  {
    id: 'dev-9',
    name: 'Sprinkler Zone Alpha',
    type: 'irrigation',
    room: 'Backyard',
    isOn: false,
    value: 0,
    metricUnit: 'L/min',
    energyUsage: 0,
    status: 'online',
    lastSeen: '1 hour ago',
  },
  {
    id: 'dev-10',
    name: 'Study Desk Monolith',
    type: 'light',
    room: 'Home Office',
    isOn: true,
    value: 90,
    metricUnit: '%',
    energyUsage: 15,
    status: 'online',
    lastSeen: 'Just now',
  },
];

export const initialAutomations = [
  {
    id: 'auto-1',
    name: 'Sunset Pathway Lighting',
    triggerType: 'time',
    triggerDetail: '19:00',
    targetDeviceId: 'dev-5',
    action: 'turn_on',
    actionValue: 80,
    isEnabled: true,
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  },
  {
    id: 'auto-2',
    name: 'Midnight Lockdown',
    triggerType: 'time',
    triggerDetail: '23:30',
    targetDeviceId: 'dev-4',
    action: 'turn_on',
    actionValue: 100,
    isEnabled: true,
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
  },
  {
    id: 'auto-3',
    name: 'Morning Coffee Pre-Heat',
    triggerType: 'time',
    triggerDetail: '07:15',
    targetDeviceId: 'dev-7',
    action: 'turn_on',
    isEnabled: false,
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
  },
  {
    id: 'auto-4',
    name: 'Eco Temp Away Mode',
    triggerType: 'time',
    triggerDetail: '09:00',
    targetDeviceId: 'dev-2',
    action: 'set_value',
    actionValue: 78,
    isEnabled: true,
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'],
  },
];

export const initialLogs = [
  {
    id: 'log-1',
    timestamp: '05:42:15 AM',
    deviceId: 'dev-10',
    deviceName: 'Study Desk Monolith',
    type: 'control',
    message: 'Value set to 90% by auto routine',
    room: 'Home Office',
  },
  {
    id: 'log-2',
    timestamp: '05:30:00 AM',
    deviceId: 'dev-6',
    deviceName: 'Backyard Cam AI',
    type: 'info',
    message: 'Daily status diagnostic reports normal',
    room: 'Backyard',
  },
  {
    id: 'log-3',
    timestamp: '04:12:10 AM',
    deviceId: 'dev-4',
    deviceName: 'Front Door Deadbolt',
    type: 'success',
    message: 'Manual lock mechanism engaged',
    room: 'Garage',
  },
  {
    id: 'log-4',
    timestamp: '03:10:04 AM',
    deviceId: 'dev-8',
    deviceName: 'RoboVac Clean sweep',
    type: 'warning',
    message: 'Docked successfully. Battery charging from low state (12%)',
    room: 'Living Room',
  }
];

export const energyMockHistory = [
  { time: '12 AM', lighting: 15, heating: 140, appliances: 85, total: 240 },
  { time: '02 AM', lighting: 5, heating: 120, appliances: 85, total: 210 },
  { time: '04 AM', lighting: 5, heating: 130, appliances: 110, total: 245 },
  { time: '06 AM', lighting: 40, heating: 160, appliances: 120, total: 320 },
  { time: '08 AM', lighting: 110, heating: 190, appliances: 450, total: 750 },
  { time: '10 AM', lighting: 30, heating: 110, appliances: 380, total: 520 },
  { time: '12 PM', lighting: 20, heating: 80, appliances: 240, total: 340 },
  { time: '02 PM', lighting: 25, heating: 95, appliances: 210, total: 330 },
  { time: '04 PM', lighting: 55, heating: 130, appliances: 280, total: 465 },
  { time: '06 PM', lighting: 180, heating: 210, appliances: 640, total: 1030 },
  { time: '08 PM', lighting: 220, heating: 180, appliances: 510, total: 910 },
  { time: '10 PM', lighting: 120, heating: 160, appliances: 190, total: 470 },
];
